config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/doctors/:id', to: 'doctors#show'

  get '/hospitals/:id', to: 'hospitals#show'
  get '/hospitals/:id/patients', to: 'hospitalpatients#index'
  get '/hospitals/:id/doctor/new', to: 'doctors#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc_patient.rb
class DocPatient < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :doctor_patients, dependent: :destroy
  has_many :patients, through: :doctor_patients


  validates_presence_of :name,
                        :specialty,
                        :education

  def by_age
    patients.order(:age)
  end
end

app/models/doctor_patient.rb
class DoctorPatient < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors, dependent: :destroy


  validates_presence_of :name,
                        :address,
                        :city,
                        :state,
                        :zip
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :doctor_patients

  has_many :doctors, through: :doctor_patients


  validates_presence_of :name,
                        :age

end

app/models/patient_doctor.rb
class PatientDoctor < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctor_patients_controller.rb
class DoctorPatientsController < ApplicationController

    def destroy 
        doctor = Doctor.find(params[:doc_id])
        patient_to_remove = DoctorPatient.where(doctor_id: params[:doc_id]).where(patient_id: params[:id])
        patient_to_remove.first.delete
        redirect_to "/doctors/#{doctor.id}"
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @hospital = Hospital.find(params[:id])
    
  end
end

app/controllers/hospital_doctors_controller.rb
class HospitalDoctorsController < ApplicationController 

    def new 
        @hospital = Hospital.find(params[:id])
    end

    def create
        hospital = Hospital.find(params[:id])
        doctor = Doctor.new(hospital_doctor_params)
        doctor.hospital_id = hospital.id
        doctor.save
        redirect_to "/hospitals/#{hospital.id}"
    end 

    private

    def hospital_doctor_params
        params.permit(:name, :specialty, :education)
    end 
end 

app/controllers/hospital_patients_controller.rb
class HospitalPatientsController < ApplicationController

  def index
    @hospital = Hospital.find(params[:id])
    @hospital.doctors.each do |doctor|
      doctor.patients.order(:age)
    end
  end
end

app/controllers/hospitalpatients_controller.rb
class HospitalpatientsController < ApplicationController

  def index
    @hospital = Hospital.find(params[:id])
  end

end

app/controllers/hospitals/doctors_controller.rb
class Hospitals::DoctorsController <ApplicationController

  def new
    @hospital = Hospital.find(params[:id])
  end

  def create
    @hospital = Hospital.find(params[:id])
    @doctor = @hospital.doctors.create(doctor_params)
    redirect_to "/hospitals/#{@hospital.id}"
  end

  private

  def doctor_params
    params.permit(:name, :specialty, :education)
  end
end

app/controllers/hospitals/patients_controller.rb
class Hospitals::PatientsController <ApplicationController

  def index
    @patients = Hospital.find(params[:id]).all_patients_sorted_by_age
  end

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def show
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/hospitals_patients_controller.rb
class HospitalsPatientsController < ApplicationController
  def index
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/patient_doctor_controller.rb
class PatientDoctorController < ApplicationController

  def destroy 
    doctor = Doctor.find(params[:doctor_id])
    doctor.patients.delete(params[:patient_id])
    redirect_to "/doctors/#{doctor.id}"
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @hospital = Hospital.find(params[:hospital_id])
    @patients = Patient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/edit.html.erb
<h2>Assign <%= @doctor.name%> to new hospital </h2>

<%=form_tag "/doctors/#{@doctor.id}", method: :patch do %>

    <%= label_tag "New hospital ID" %>
    <%= number_field_tag :hosp_id %>

    <%=submit_tag "Add #{@doctor.name} to this hospital"%>
<% end %>

app/views/doctors/edit_hospital.html.erb
<h1>Reassign Hospital for <%= @doctor.name %></h1>

<%= form_tag "/doctors/#{@doctor.id}/update_hospital", method: :patch do |f| %>

<%= label_tag :hospital_id, "Hospital ID:" %>
<%= text_field_tag "hospital_id" %><br>

<%= submit_tag "Add #{@doctor.name} to this hospital" %>
<% end %>

app/views/doctors/index.html.erb
<h1>All Doctors at <%= link_to "#{@hospital.name}", hospital_path(@hospital.id) %></h1>

<% @hospital.doctors.each do |doctor| %>
  <div>
    <%= link_to "#{doctor.name}", doctor_path(doctor.id) %>
  </div>
<% end %>

app/views/doctors/new.html.erb
<h1><%= "New Doctor Hire for #{@hospital.name}" %></h1>

<center>
  <%= form_for [:hospital, @doctor] do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name%>

    <%= f.label :specialty %>
    <%= f.text_field :specialty %>

    <%= f.label :education %>
    <%= f.text_field :education %>

    <%= f.submit %>
  <% end %>
</center>

app/views/doctors/reassign.html.erb
<h2>Reassign Doctor</h2>

<%= form_for @doctor do |f| %>
  <%= f.label :hospital_id %>
  <%= f.text_field :hospital_id %>

  <%= f.submit "Add #{@doctor.name} to this hospital" %>
<% end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<p>Specialty: <%= @doctor.specialty %></p>
<p>Education: <%= @doctor.education %></p>
<p>Education: <%= @doctor.hospital.name %></p>
<h3> Patients: </h3><br>
<% @doctor.doctor_patients.each do |doctor_patient| %>
  Name: <%= doctor_patient.patient.name %><br>
<% end %>

app/views/features/doctors/show.html.erb
<h1> Doctors </h1>

app/views/hospital_doctors/new.html.erb
<h1>New Doctor Form</h1>

<%= form_tag "/hospitals/#{@hospital.id}/doctors", method: :post do %>

    <%= label_tag "Name"%><br>
    <%= text_field_tag :name%><br>

    <%= label_tag "Specialty"%><br>
    <%= text_field_tag :specialty%><br>

    <%= label_tag "Education"%><br>
    <%= text_field_tag :education%><br>

    <%= submit_tag "Add this Doctor to #{@hospital.name}" %>
<% end %>

app/views/hospital_patients/index.html.erb
<h1><%= @hospital.name %></h1>
<h3> Patients: </h3><br/> 
<% @hospital.doctors.each do |doctor| %>
  <% doctor.ordered_names.each do |patient| %>
    <li><%= patient.name %></li><br/>
  <% end %>
<% end %>

app/views/hospitalpatients/index.html.erb
<h1> Hospital's Patients </h1>

<p><% @hospital.doctors.each do |doctor| %></p>
  <p><% doctor.by_age.each_with_index do |patient, index| %></p>
   <p id="patient-<%= index %>"><%= patient.name %></p>
  <% end %>
<% end %>

app/views/hospitals/doctors/new.html.erb
<h1>New Doctor Hire for <%= @hospital.name %></h1>

<%= form_tag "/hospitals/#{@hospital.id}/doctors/create" do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= label_tag :specialty %>
  <%= text_field_tag :specialty %>

  <%= label_tag :education %>
  <%= text_field_tag :education %>

  <%= submit_tag 'Submit' %>
<% end %>

app/views/hospitals/index.html.erb
<h1>All Hospitals</h1>

<% @hospitals.each do |hospital| %>
  <p>
    <%= link_to "#{hospital.name}", hospital_path(hospital.id) %>
  </p>
<% end %>

app/views/hospitals/patients/index.html.erb
<h1>Hospital Patients</h1>

<p><% @patients.each do |patient| %></p>
  <p> <%= patient.name %>
<% end %>

app/views/hospitals/show.html.erb
<h1><%= @hospital.name %></h1>
<p class="address"><%= @hospital.address %></p>
<p class="address"><%= @hospital.city %>, <%= @hospital.state %> <%= @hospital.zip %></p>
<p class="doctors">Number of Doctors: <%= @hospital.doctors.count %></p>
<section class="doc_univ">
  <h2>Universities That Doctors Have Attended:</h2>
  <% @hospital.doctors.each do |doctor| %>
     <%= doctor.education %><br>
  <% end.uniq %>
</section>

<p><%= link_to "This Hospital's Patients", "/hospitals/#{@hospital.id}/patients" %></p>
<p><%= link_to "Add Doctor", "/hospitals/#{@hospital.id}/doctor/new" %></p>

app/views/hospitals_patients/index.html.erb
<h2> <%= @hospital.name %>'s Patients </h2>

<p>Patients: </p>
<% @hospital.doctors.each do |doctor| %>
  <%= doctor.patients.order_by_oldest %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= yield(:title) if content_for(:title)%>
      SeattleGrace
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>